version: '3.8'

services:
  cryptopro:
    image: api.registry.viomitra.ru/cert:latest
    volumes:
      - ./cryptopro-data:/var/opt/cprocsp/
      - ./cryptopro-etc:/etc/opt/cprocsp/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 30s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.cryptopro-http.rule=Host(`cert.viomitra.ru`)
        - traefik.http.routers.cryptopro-http.entrypoints=http
        - traefik.http.routers.cryptopro-http.middlewares=https-redirect
        - traefik.http.routers.cryptopro-https.rule=Host(`cert.viomitra.ru`)
        - traefik.http.routers.cryptopro-https.entrypoints=https
        - traefik.http.routers.cryptopro-https.tls=true
        - traefik.http.routers.cryptopro-https.tls.certresolver=le
        - traefik.http.services.cryptopro.loadbalancer.server.port=80